config/routes.rb
Rails.application.routes.draw do
  resources :simple_articles

  match '/file_editor/(*path)', to: 'file_editor#index', via: [:get, :post], format: false, as: :file_editor
  match '/file_editor(*path)', to: 'file_editor#index', via: [:get, :post], format: false, as: :file

end

app/models/simple_article.rb
class SimpleArticle < ActiveRecord::Base
  attr_accessible :published, :name, :short_description, :full_description, :release_date

  has_attached_file :avatar, :styles => { :article_list_small_thumb => '360x300#', related_irticle_thumb: '600x500#'},
                    :url  => "/assets/#{self.name.underscore}/:id/avatar/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/#{self.name.underscore}/:id/avatar/:style/:basename.:extension",
                    convert_options: {
                        article_list_small_thumb: "-quality 94 -interlace Plane",
                        related_irticle_thumb: "-quality 94 -interlace Plane"
                    }

  has_attached_file :banner, :styles => { :banner => '2100x500#'},
                    :url  => "/assets/#{self.name.underscore}/:id/banner/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/#{self.name.underscore}/:id/banner/:style/:basename.:extension",
                    convert_options: {
                        banner: "-quality 94 -interlace Plane",
                    }

  validates_attachment_file_name :avatar, :matches => [/png\Z/i, /jpe?g\Z/i, /gif\Z/i, /svg\Z/i]
  validates_attachment_file_name :banner, :matches => [/png\Z/i, /jpe?g\Z/i, /gif\Z/i, /svg\Z/i]


  [:avatar, :banner].each do |paperclip_field_name|
    attr_accessible paperclip_field_name.to_sym, "delete_#{paperclip_field_name}".to_sym, "#{paperclip_field_name}_file_name".to_sym, "#{paperclip_field_name}_file_size".to_sym, "#{paperclip_field_name}_content_type".to_sym, "#{paperclip_field_name}_updated_at".to_sym, "#{paperclip_field_name}_file_name_fallback".to_sym, "#{paperclip_field_name}_alt".to_sym

    attr_accessor "delete_#{paperclip_field_name}".to_sym
  end

  translates :name, :short_description, :full_description, :avatar_alt, :banner_alt, :versioning => :paper_trail
  accepts_nested_attributes_for :translations
  attr_accessible :translations_attributes, :translations

  class Translation
    attr_accessible :locale, :published_translation, :name, :short_description, :full_description, :address

    # def published=(value)
    #   self[:published] = value
    # end

    # rails_admin do
    #   visible false
    #   edit do
    #     field :locale, :hidden
    #     field :published_translation
    #
    #   end
    # end
  end
end

app/controllers/simple_articles_controller.rb
class SimpleArticlesController < ApplicationController
  before_action :set_simple_article, only: [:show, :edit, :update, :destroy]

  # GET /simple_articles
  # GET /simple_articles.json
  def index
    @simple_articles = SimpleArticle.all
  end

  # GET /simple_articles/1
  # GET /simple_articles/1.json
  def show
  end

  # GET /simple_articles/new
  def new
    @simple_article = SimpleArticle.new
  end

  # GET /simple_articles/1/edit
  def edit
  end

  # POST /simple_articles
  # POST /simple_articles.json
  def create
    @simple_article = SimpleArticle.new(simple_article_params)

    respond_to do |format|
      if @simple_article.save
        format.html { redirect_to @simple_article, notice: 'Simple article was successfully created.' }
        format.json { render :show, status: :created, location: @simple_article }
      else
        format.html { render :new }
        format.json { render json: @simple_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /simple_articles/1
  # PATCH/PUT /simple_articles/1.json
  def update
    respond_to do |format|
      if @simple_article.update(simple_article_params)
        format.html { redirect_to @simple_article, notice: 'Simple article was successfully updated.' }
        format.json { render :show, status: :ok, location: @simple_article }
      else
        format.html { render :edit }
        format.json { render json: @simple_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /simple_articles/1
  # DELETE /simple_articles/1.json
  def destroy
    @simple_article.destroy
    respond_to do |format|
      format.html { redirect_to simple_articles_url, notice: 'Simple article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_simple_article
      @simple_article = SimpleArticle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def simple_article_params
      params.require(:simple_article).permit(:name, :short_description, :full_description, :published)
    end
end

app/helpers/simple_articles_helper.rb
module SimpleArticlesHelper
end

app/views/simple_articles/_form.html.erb
<%= form_for(@simple_article) do |f| %>
  <% if @simple_article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@simple_article.errors.count, "error") %> prohibited this simple_article from being saved:</h2>

      <ul>
      <% @simple_article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :short_description %><br>
    <%= f.text_area :short_description %>
  </div>
  <div class="field">
    <%= f.label :full_description %><br>
    <%= f.text_area :full_description %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/simple_articles/edit.html.erb
<h1>Editing simple_article</h1>

<%= render 'form' %>

<%= link_to 'Show', @simple_article %> |
<%= link_to 'Back', simple_articles_path %>

app/views/simple_articles/index.html.erb
<h1>Listing simple_articles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Short description</th>
      <th>Full description</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @simple_articles.each do |simple_article| %>
      <tr>
        <td><%= simple_article.name %></td>
        <td><%= simple_article.short_description %></td>
        <td><%= simple_article.full_description %></td>
        <td><%= simple_article.published %></td>
        <td><%= link_to 'Show', simple_article %></td>
        <td><%= link_to 'Edit', edit_simple_article_path(simple_article) %></td>
        <td><%= link_to 'Destroy', simple_article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Simple article', new_simple_article_path %>

app/views/simple_articles/new.html.erb
<h1>New simple_article</h1>

<%= render 'form' %>

<%= link_to 'Back', simple_articles_path %>

app/views/simple_articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @simple_article.name %>
</p>

<p>
  <strong>Short description:</strong>
  <%= @simple_article.short_description %>
</p>

<p>
  <strong>Full description:</strong>
  <%= @simple_article.full_description %>
</p>

<p>
  <strong>Published:</strong>
  <%= @simple_article.published %>
</p>

<%= link_to 'Edit', edit_simple_article_path(@simple_article) %> |
<%= link_to 'Back', simple_articles_path %>